spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fteamlpt_well_clothes?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
#      javax:
#        persistence:
#          timezone: Asia/Ho_Chi_Minh
      format-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


application:
  security:
    jwt:
      secret-key: 566D597133743677397A244326452948404D635166546A576E5A723475377821
      expiration: 8640000
      refresh-token:
        expiration: 604800000
